import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { ThemeProvider } from "../components/theme-provider";
import "./globals.css";
import { cn } from "../lib/utils";
import { TaskProvider } from "@/context/TaskContext";
import { TokenProvider } from "@/context/TokenContext";
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
import { Toaster } from "@/components/ui/Toaster";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {/* <TaskProvider> */}
          <TokenProvider>{children}</TokenProvider>
          {/* </TaskProvider> */}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
